version: '3'

services:
  gunicorn:
   build: .
   image: gunicorn:20.1.0
   container_name: gunicorn
   volumes:
    - .:/usr/src/app
    - gunicorn:/var/run/gunicorn
   env_file: docker.env
   stdin_open: true
   tty: true
   restart: always

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nginx
    restart: always
    environment:
      STAGE: 'local'
      # STAGE: 'production'
      # DOMAINS: 'shitsumonbako.com -> http://nginx:80'
      DOMAINS: 'localhost -> http://nginx:80'
      # FORCE_RENEW: 'true'
    volumes:
      - https-portal-data:/var/lib/https-portal

  nginx:
    image: nginx:1.17.7
    container_name: nginx
    depends_on:
      - gunicorn
    expose:
      - 80
    volumes:
      - ./gunicorn.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/boardapp-nginx/static
      - gunicorn:/var/run/gunicorn
    restart: always

volumes:
  gunicorn:
    driver: local
  https-portal-data:
